# NumPy Examples

See https://numpy.org/doc/stable/reference/arrays.ndarray.html

In [1]:
import numpy as np

x = np.array([[1,2,3],[4,5,6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [2]:
x[:,1]

array([2, 5])

In [3]:
v = np.array([1, 0, -1])
v

array([ 1,  0, -1])

In [4]:
x @ v

array([-2, -2])

In [5]:
from numpy.linalg import det

m = np.array([[3,5,2], [7,3,1], [9,4,2]])
m

array([[3, 5, 2],
       [7, 3, 1],
       [9, 4, 2]])

In [6]:
det(m)

np.float64(-17.00000000000001)

In [7]:
np.transpose(m)

array([[3, 7, 9],
       [5, 3, 4],
       [2, 1, 2]])

In [8]:
m.T

array([[3, 7, 9],
       [5, 3, 4],
       [2, 1, 2]])

In [9]:
m @ m.T

array([[ 38,  38,  51],
       [ 38,  59,  77],
       [ 51,  77, 101]])

In [10]:
m.T @ m

array([[139,  72,  31],
       [ 72,  50,  21],
       [ 31,  21,   9]])

Quarter turn about the x-axis: Q_x

In [11]:
Qx = np.array([[1,0,0],[0,0,1],[0,-1,0]])
Qx

array([[ 1,  0,  0],
       [ 0,  0,  1],
       [ 0, -1,  0]])

In [12]:
Qx @ Qx.T

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [13]:
Hx = Qx @ Qx
Hx

array([[ 1,  0,  0],
       [ 0, -1,  0],
       [ 0,  0, -1]])

In [14]:
Fx = Hx @ Hx
Fx

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [15]:
Qx @ Qx.T

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [16]:
det(Qx)

np.float64(1.0)

In [17]:
Qy = np.array([[0,0,1], [0,1,0], [-1,0,0]])
Qy

array([[ 0,  0,  1],
       [ 0,  1,  0],
       [-1,  0,  0]])

In [18]:
det(Qy)

np.float64(1.0)

In [19]:
Qy@Qy.T

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [20]:
Qz=np.array([[0,1,0],[-1,0,0],[0,0,1]])
Qz

array([[ 0,  1,  0],
       [-1,  0,  0],
       [ 0,  0,  1]])

In [21]:
Qz @ Qz.T

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [22]:
det(Qz)

np.float64(1.0)

In [23]:
import numpy as np
np.indices((3,3))

array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])

In [24]:
v = np.array([1,1,1])
v

array([1, 1, 1])

In [25]:
def mk_powers(M, n):
    powers = []
    d, _ = M.shape
    P = np.eye(d)
    while True:
        powers.append(P)
        if len(powers) == n:
            break
        P = P @ M
    return powers

mk_powers(Qx, 4)
    

[array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]),
 array([[ 1.,  0.,  0.],
        [ 0.,  0.,  1.],
        [ 0., -1.,  0.]]),
 array([[ 1.,  0.,  0.],
        [ 0., -1.,  0.],
        [ 0.,  0., -1.]]),
 array([[ 1.,  0.,  0.],
        [ 0.,  0., -1.],
        [ 0.,  1.,  0.]])]

In [26]:
def mk_face(v, Q):
    vs = [v]
    for i in range(3):
        v = Q @ v
        vs.append(v)
    return np.array(vs)

mk_face(v, Qx)

array([[ 1,  1,  1],
       [ 1,  1, -1],
       [ 1, -1, -1],
       [ 1, -1,  1]])